{% set name = "model_catalogs" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/model_catalogs-{{ version }}.tar.gz
  sha256: 2f7e81e43ba25a594487bd57b6c9706508b1b4520f07284e0a5eefda92035811

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - cf_xarray
    - datetimerange
    - intake-xarray
    - appdirs
    - requests
    - netcdf4
    - pip
    - intake
    - xarray
    - siphon
    - pandas
    - dask-core
    - numpy

test:
  imports:
    - model_catalogs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NOAA-ORR-ERD/model_catalogs
  summary: Catalogs for known models
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - kthyng
